"""CLI & Example Custom Implementation for Video Render Engine.

Demonstrates:
1. How a user implements `BaseVideoRenderer` using their own preferred tool.
2. How `AntiReupEngine` generates randomized video/audio filter chains and container metadata.
3. How `VideoRenderEngine` runs multiple video renders concurrently across parallel threads.
4. How each thread maintains an isolated in-memory log buffer (no disk I/O for logs).

Run directly:
    python app/services/video_render_engine/main.py
"""

import argparse
import logging
from pathlib import Path
import sys
import time

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.services.video_render_engine import (
    allocate_next_output_path,
    AntiReupEngine,
    AntiReupProfile,
    BaseVideoRenderer,
    MacOSVideoRenderer,
    WindowsVideoRenderer,
    get_platform_renderer,
    RenderResult,
    ScenePlan,
    TaskLogger,
    VideoRenderConfig,
    VideoRenderEngine,
    VideoRenderPlan,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [MainProcess] %(message)s",
    datefmt="%H:%M:%S",
)


class ExampleUserRenderer(BaseVideoRenderer):
    """Example implementation of BaseVideoRenderer demonstrating active Anti-Reup usage.

    Users implement their preferred video rendering logic here (e.g. calling FFmpeg CLI,
    GStreamer, hardware encoders, MoviePy, or platform-native SDKs) and apply the
    filter chains generated by AntiReupEngine.
    """

    @property
    def renderer_name(self) -> str:
        return "ExampleUserRenderer"

    def validate_environment(self) -> bool:
        """User checks if their rendering tools are installed and ready."""
        return True

    def render_plan(
        self,
        plan: VideoRenderPlan,
        source_folder: Path,
        config: VideoRenderConfig,
        profile: AntiReupProfile,
        task_logger: TaskLogger,
    ) -> RenderResult:
        """User implements their custom rendering process for a single plan.

        Notice how AntiReupEngine generates the exact filter chains for video, audio, and metadata!
        """
        task_logger.info(f"==> Bắt đầu xử lý {len(plan.scenes)} scenes cho kịch bản: '{plan.title}'")

        # 1. Đọc các thông số ngẫu nhiên từ AntiReupProfile
        task_logger.info("[Anti-Reup] Thông số đã được ngẫu nhiên hóa:")
        for param_key, param_val in profile.params.items():
            task_logger.info(f"   • {param_key}: {param_val}")

        base_dest_dir = config.output_dir or (source_folder.parent / "storage" / "outputs")
        if plan.company_name or not plan.output_filename:
            output_file = allocate_next_output_path(
                base_output_dir=base_dest_dir,
                company_name=plan.company_name,
                sequence_hint=plan.video_index,
            )
            dest_dir = output_file.parent
        else:
            dest_dir = base_dest_dir
            dest_dir.mkdir(parents=True, exist_ok=True)
            output_file = dest_dir / plan.output_filename

        # 2. Xử lý từng phân cảnh theo kịch bản (scenes)
        total_duration = 0.0
        for i, scene in enumerate(plan.scenes):
            task_logger.info(f"   [Scene {i+1}/{len(plan.scenes)}] '{scene.content[:30]}...'")
            total_duration += 2.0  # Giả lập thời lượng mỗi scene
            time.sleep(0.3)

        # 3. Tạo file thành phẩm mô phỏng kèm thông số Anti-Reup
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(f"Rendered video data for {plan.plan_id}\n")
            for param_key, param_val in profile.params.items():
                f.write(f"{param_key}: {param_val}\n")

        file_size = output_file.stat().st_size
        task_logger.info(f"==> Render hoàn tất thành công -> {output_file.name} ({file_size} bytes)")

        return RenderResult(
            plan_id=plan.plan_id,
            output_path=output_file,
            duration=round(total_duration, 2),
            file_size_bytes=file_size,
            metadata=dict(profile.params),
        )


def build_sample_plans() -> list[VideoRenderPlan]:
    """Generate 3 distinct sample video plans to demonstrate parallel execution."""
    return [
        VideoRenderPlan(
            plan_id="plan_tuyendung_ai",
            company_name="TechNova",
            video_index=1,
            title="Tuyển Kỹ Sư AI TechNova",
            scenes=[
                ScenePlan(scene_index=0, content="🔥 Tuyển gấp Kỹ Sư AI"),
                ScenePlan(scene_index=1, content="Lương 25 - 40 Triệu Hybrid"),
                ScenePlan(scene_index=2, content="Gửi CV về hr@technova.vn"),
            ],
        ),
        VideoRenderPlan(
            plan_id="plan_marketing_lead",
            company_name="TechNova",
            video_index=2,
            title="Tuyển Trưởng Phòng Marketing",
            scenes=[
                ScenePlan(scene_index=0, content="🚀 Tìm kiếm Trưởng Phòng Marketing"),
                ScenePlan(scene_index=1, content="Môi trường năng động, thưởng quý"),
                ScenePlan(scene_index=2, content="Ứng tuyển ngay tại link bio!"),
            ],
        ),
        VideoRenderPlan(
            plan_id="plan_frontend_dev",
            company_name="TechNova",
            video_index=3,
            title="Tuyển Senior Frontend Developer",
            scenes=[
                ScenePlan(scene_index=0, content="💻 Cơ hội Senior React/Flutter Dev"),
                ScenePlan(scene_index=1, content="Phúc lợi MacBook M-Series + Bảo hiểm"),
                ScenePlan(scene_index=2, content="Tham gia phỏng vấn tuần này"),
            ],
        ),
    ]


def main():
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
            sys.stderr.reconfigure(encoding="utf-8")
        except Exception:
            pass

    parser = argparse.ArgumentParser(description="Video Render Engine CLI & Multi-Threading Demo")
    parser.add_argument(
        "--source-folder",
        type=str,
        default="assets/samples/company_media",
        help="Thư mục chứa video/ảnh tư liệu",
    )
    parser.add_argument(
        "--max-workers",
        type=int,
        default=3,
        help="Số lượng video render song song đồng thời",
    )
    parser.add_argument(
        "--anti-reup-level",
        type=str,
        choices=["none", "low", "medium", "high"],
        default="medium",
        help="Mức độ thuật toán chống re-up",
    )
    parser.add_argument(
        "--renderer",
        type=str,
        choices=["auto", "windows", "macos", "example"],
        default="auto",
        help="Chọn renderer: 'auto' (tự động theo hệ điều hành), 'windows' (NVIDIA NVENC), 'macos' (VideoToolbox) hoặc 'example' (giả lập)",
    )
    parser.add_argument(
        "--fit-mode",
        type=str,
        choices=["crop", "pad"],
        default="crop",
        help="Cơ chế chuẩn hóa khung hình: 'crop' (lấp đầy) hoặc 'pad' (thêm viền)",
    )
    args = parser.parse_args()

    source_path = PROJECT_ROOT / args.source_folder
    output_path = PROJECT_ROOT / "storage" / "outputs"

    print("=" * 75)
    print("🎬 VIDEO RENDER ENGINE - TÍCH HỢP ANTI-REUP & LOG ĐỘC LẬP ĐA LUỒNG")
    print("=" * 75)
    print(f"📁 Thư mục nguồn         : {source_path}")
    print(f"📁 Thư mục xuất video    : {output_path}")
    print(f"⚡ Số luồng render tối đa : {args.max_workers} worker threads")
    print(f"🛡️ Mức độ Anti-Reup      : {args.anti_reup_level.upper()}")
    print(f"💻 Trình Render          : {args.renderer.upper()}")
    print(f"📐 Fit Mode              : {args.fit_mode.upper()}")
    print("=" * 75)

    # 1. Khởi tạo cấu hình
    config = VideoRenderConfig(
        width=1080,
        height=1920,
        fps=30,
        max_concurrent_tasks=args.max_workers,
        anti_reup_level=args.anti_reup_level,
        output_dir=output_path,
        extra_params={"aspect_mode": args.fit_mode},
    )

    # 2. Khởi tạo renderer tương ứng
    if args.renderer == "auto":
        user_renderer = get_platform_renderer(hardware_accel=True, default_fit_mode=args.fit_mode)
    elif args.renderer == "windows":
        user_renderer = WindowsVideoRenderer(hardware_accel=True, default_fit_mode=args.fit_mode)
    elif args.renderer == "macos":
        user_renderer = MacOSVideoRenderer(hardware_accel=True, default_fit_mode=args.fit_mode)
    else:
        user_renderer = ExampleUserRenderer()

    # 3. Khởi tạo VideoRenderEngine và cấu hình thêm quy tắc random tùy chỉnh
    engine = VideoRenderEngine(
        renderer=user_renderer,
        config=config,
    )
    # Người dùng có thể tự do thêm/ghi đè bất kỳ quy tắc random nào theo ý muốn
    engine.anti_reup_engine.set_rule("rotation_angle", (-0.3, 0.3))      # Góc xoay vi mô
    engine.anti_reup_engine.set_rule("vignette_amount", (0.02, 0.06))     # Độ mờ viền góc

    # 4. Danh sách các video plan cần render
    plans = build_sample_plans()
    # Phân bổ ngẫu nhiên BGM từ assets/sounds/bgm cho mỗi plan với âm lượng 10%
    from app.services.video_render_engine.bgm_manager import allocate_bgm_for_plans
    allocated_bgm = allocate_bgm_for_plans(len(plans))
    for idx, p in enumerate(plans):
        p.bgm_path = allocated_bgm[idx]
        p.bgm_volume = 0.10
    print(f"\n🚀 Khởi chạy render song song {len(plans)} videos (mỗi plan kèm BGM ngẫu nhiên 10%)...")

    start_time = time.time()
    batch_result = engine.render_batch(
        source_folder=source_path,
        plans=plans,
        max_workers=args.max_workers,
        on_progress=lambda res: print(f"   [Progress Update] Đã render xong: {res.plan_id} -> {res.output_path.name}"),
    )
    total_elapsed = time.time() - start_time

    print("\n" + "=" * 75)
    print("📊 BÁO CÁO KẾT QUẢ BATCH RENDER & CÁC THÔNG SỐ RANDOM HÓA (ANTI-REUP)")
    print("=" * 75)
    print(f"Tổng số videos yêu cầu: {batch_result.total_plans}")
    print(f"Thành công            : {batch_result.successful_renders}")
    print(f"Thất bại              : {batch_result.failed_renders}")
    print(f"Tổng thời gian chạy   : {total_elapsed:.2f}s")
    print("\nChi tiết các thông số đã được Randomize độc lập cho từng video:")
    for res in batch_result.results:
        profile = res.anti_reup_profile
        print(f"\n  • Video Plan : {res.plan_id}")
        print(f"    - File ra  : {res.output_path}")
        print(f"    - Thời gian: {res.render_time_seconds}s (Thời lượng: {res.duration}s)")
        if profile:
            print("    - 🎲 Danh sách thông số đã random (profile.params):")
            for k, v in profile.params.items():
                print(f"       + {k:20s}: {v}")
        print(f"    - 📜 Số dòng log in-memory: {len(res.logs)}")
    print("=" * 75)


if __name__ == "__main__":
    main()
