"""
Module TTS Engine: Dịch vụ chuyển đổi văn bản sang giọng nói tiếng Việt thuần VieNeu-TTS (v3 Turbo, 48 kHz).
"""

from app.services.tts_engine.constants import (
    DEFAULT_LANGUAGE,
    DEFAULT_MODEL_MODE,
    DEFAULT_SAMPLE_RATE,
    DEFAULT_SPEED,
    DEFAULT_VOICE,
    DEFAULT_BASE_TARGET_WPS,
    DEFAULT_SYNC_VOICE_SPEED,
    MIN_SAFE_SPEED_FACTOR,
    MAX_SAFE_SPEED_FACTOR,
    DEFAULT_TEMPERATURE,
    DEFAULT_TOP_P,
    DEFAULT_REPETITION_PENALTY,
    DEFAULT_SILENCE_P,
    DEFAULT_CROSSFADE_P,
    DEFAULT_TRIM_SILENCE_THRESHOLD_DB,
    DEFAULT_TRIM_MARGIN_SEC,
    DEFAULT_MAX_INTERNAL_SILENCE_SEC,
    DEFAULT_TARGET_INTERNAL_SILENCE_SEC,
    format_emotion_cues,
    estimate_syllables,
    trim_silence_edges,
    compress_internal_silence,
    VOICE_REGION_GENDER_MAP,
    VieNeuVoice,
    VoiceGender,
    VoiceRegion,
    get_all_voice_names,
    get_preset_voice_for_clone,
    parse_voice_filename,
    resolve_voice,
)
from app.services.tts_engine.engine import TTSEngine

__all__ = [
    "TTSEngine",
    "VieNeuVoice",
    "VoiceRegion",
    "VoiceGender",
    "VOICE_REGION_GENDER_MAP",
    "parse_voice_filename",
    "get_preset_voice_for_clone",
    "DEFAULT_MODEL_MODE",
    "DEFAULT_LANGUAGE",
    "DEFAULT_VOICE",
    "DEFAULT_SPEED",
    "DEFAULT_SAMPLE_RATE",
    "DEFAULT_BASE_TARGET_WPS",
    "DEFAULT_SYNC_VOICE_SPEED",
    "MIN_SAFE_SPEED_FACTOR",
    "MAX_SAFE_SPEED_FACTOR",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TOP_P",
    "DEFAULT_REPETITION_PENALTY",
    "DEFAULT_SILENCE_P",
    "DEFAULT_CROSSFADE_P",
    "DEFAULT_TRIM_SILENCE_THRESHOLD_DB",
    "DEFAULT_TRIM_MARGIN_SEC",
    "DEFAULT_MAX_INTERNAL_SILENCE_SEC",
    "DEFAULT_TARGET_INTERNAL_SILENCE_SEC",
    "format_emotion_cues",
    "estimate_syllables",
    "trim_silence_edges",
    "compress_internal_silence",
    "get_all_voice_names",
    "resolve_voice",
]

